### PR TITLE
ERSSUP-59667 - Policy to translate NHSD-eRS-On-Behalf-Of-User-ID header to x-ers-obo-user-id

### PR DESCRIPTION
**Pull request by nhsd-nigel-mellor**
## Summary
* Routine Change
* :exclamation: Breaking Change
* :robot: Operational or Infrastructure Change
* :sparkles: New Feature
* :warning: Potential issues that might be caused by this change

Add any other relevant notes or explanations here. **Remove this line if you have nothing to add.**

## Reviews Required
* [x] Dev
* [ ] Test
* [ ] Tech Author
* [ ] Product Owner

## Review Checklist
:information_source: This section is to be filled in by the **reviewer**.

* [x] I have reviewed the changes in this PR and they fill all or part of the acceptance criteria of the ticket, and the code is in a mergeable state.
* [x] If there were infrastructure, operational, or build changes, I have made sure there is sufficient evidence that the changes will work.
* [ ] I have ensured the changelog has been updated by the submitter, if necessary.

### CODE REVIEW

**Review by nhsd-jack-wainwright — APPROVED** [review]
Looks good to me 🙂

**Comment by andrewclark2020** [comment]
Since you've added and renamed headers it would be good to get them into the tests/integration/test_headers.py test

**Review by andrewclark2020 — APPROVED** [review]
Yep tests now correctly asserting the value.

**Review by nhsd-jack-wainwright — DISMISSED** [review]

**Review by andrewclark2020 — DISMISSED** [review]
Approved

**Pull request merged**
