### PR TITLE
[ERSSUP-67516]-[]-[Updated API document for 423 Locked Response]-[RG]

### PR DESCRIPTION
**Pull request by RajaGovindharaj16**
## Summary
* Routine Change
* :exclamation: Breaking Change
* :robot: Operational or Infrastructure Change
* :sparkles: New Feature
* :warning: Potential issues that might be caused by this change

Add any other relevant notes or explanations here. **Remove this line if you have nothing to add.**

## Reviews Required
* [x] Dev
* [ ] Test
* [ ] Tech Author
* [ ] Product Owner

## Review Checklist
:information_source: This section is to be filled in by the **reviewer**.

* [ ] I have reviewed the changes in this PR and they fill all or part of the acceptance criteria of the ticket, and the code is in a mergeable state.
* [ ] If there were infrastructure, operational, or build changes, I have made sure there is sufficient evidence that the changes will work.
* [ ] I have ensured the changelog has been updated by the submitter, if necessary.

### CODE REVIEW

**Review by nhsd-jack-wainwright — COMMENTED** [review]
Looks good to me 🙂, just a couple very minor comments.

**Review by RajaGovindharaj16 — COMMENTED** [review]
same request to change same resource

**Review by RajaGovindharaj16 — COMMENTED** [review]
The NHS e-Referral Service (e-RS) implements pessimistic locking functionality in order to prevent multiple users/systems attempting to update the same resource at the same time.

The e-RS API automatically acquires the lock on the behalf of the caller, within the scope of the request. When an endpoint call is received to update a resource, that resource will be locked for the duration of the request.

API callers should not attempt to make simultaneous requests to update the same resource. Any attempt to do so will result in a 423 (Locked) response. If a 423 response is received, then another system/user may be in the process of updating the resource. It will be necessary to fetch the resource again and re-try the request at a later time.

**Review by nhsd-jack-wainwright — COMMENTED** [review]
Looks good to me 👍

**Review by nhsd-jack-wainwright — APPROVED** [review]
Looks good 👍

**Pull request merged**
